
server:
  port: 8800



spring:
  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/car_space_renting_database?serverTimezone=UTC&characterEncoding=UTF-8
    username: letsquit
    password: 5355526

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.unsw.back_end
